import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";

import { Breadcrumbs } from "@/components/layout/Breadcrumbs";
import { PrimaryHeader } from "@/components/common/PrimaryHeader";

import { Barometers } from "./_components/Barometers";
import { Certs } from "./_components/Certs";

import {
  SKILL_DATA_MANAGEMENT,
  SKILL_DATA_FRONTEND,
  SKILL_DATA_BACKEND,
  CERTS_DATA,
} from "./_data";

export const metadata: Metadata = {
  title: "About | PORTFOLIO-S",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <>
      <Breadcrumbs directory={[{ name: "About", href: "/about" }]} />
      <div className="px-4">
        <main className="max-w-[1024px] m-auto py-4">
          <PrimaryHeader
            text_ja="スキル詳細"
            text_en="About"
            className="mb-6"
          />
          <div className="flex flex-wrap mb-5 text-small leading-[2em]">
            {/* <p className="w-full mb-2 text-medium leading-1.5">
              堀江 真悟
              <i className="not-italic ml-1 text-xs leading-2.25">
                Shingo Horie
              </i>
            </p> */}
            {/* <figure className="flex-grow-0 flex-shrink-0 flex-basis-auto w-[120px] mr-3 mb-1">
              <Image
                src="/about/img_portrait.jpg"
                width="1615"
                height="1620"
                alt=""
                className="block w-full h-auto rounded-full"
                unoptimized
              />
              <figcaption className="text-[11px] leading-1.5 mt-1 text-gray-dark text-center">
                近影 (2025年撮影)
                <br />
                1985年生・群馬県出身
              </figcaption>
            </figure> */}

            <div className="flex-1 flex flex-col gap-[1em]">
              <p>
                フロントエンドエンジニアとしてwebのキャリアを開始。9年ほど開発の第一線に立っておりました。大規模なコーポレートサイトやブランドサイトを担当することが多く、基本設計・コンポーネント設計をはじめ、リッチな演出の実装、CMSの設計構築、保守運用など業務範囲は多岐にわたりました。
              </p>

              <p>
                多種多様な案件を経験する中で、開発現場にとってもビジネス側にとてもやさしいプロジェクト管理とはなんだろうと考え始め、これまで培ってきた経験値をもとにPL（Project
                Leader）に転向。「自分が思う最良のマネジメント」を実践するようになりました。それが直近の４年ほどのことになります。
              </p>

              <p>
                技術者としては開発力・提案力・スピード・守備範囲の広さを持ち味としております。
                <br />
                PLとしてはていねいな管理が持ち味で、複雑な案件の進行管理を成功させたり、業務モデルや開発スキームの再定義を任せていただいております。
              </p>

              {/* <p>
                事業会社にてメディアサイトの立ち上げを担当した際に、CMSベンダーよりインタビューを受けました
                <br />
                <Link
                  href="https://microcms.io/interviews/dip"
                  target="_blank"
                  className="text-link hover:text-link-hover transition-colors duration-300"
                >
                  ›
                  導入事例インタビュー【ディップ株式会社様】従来の約3分の1の期間でサイト公開が実現。記事公開までの期間も1か月→翌日に短縮
                </Link>
              </p> */}
            </div>
          </div>

          <div className="grid grid-cols-2 gap-5">
            <div className="border border-gray-light">
              <div className="relative flex items-center h-[110px] mt-[-1px] mx-[-1px] p-2 bg-black">
                <p className="absolute top-0 left-0 w-full h-full">
                  <Image
                    src="/about/bg_skill_title_05.jpg"
                    width="960"
                    height="300"
                    alt=""
                    className="w-full h-full object-cover opacity-50"
                    unoptimized
                  />
                </p>
                <p className="relative flex-1 text-center font-medium text-xl text-white">
                  Project Managements
                </p>
              </div>
              <div className="p-3 text-small leading-1.5">
                <p>
                  関連：
                  <Link
                    href="/managements"
                    className="text-link hover:text-link-hover transition-colors duration-300"
                  >
                    Manegements - PLとしての実績一覧
                  </Link>
                </p>
                <hr className="block h-[1px] my-3 p-0 border-none bg-gray-light" />

                <Barometers
                  skills={SKILL_DATA_MANAGEMENT}
                  inexperienced={`予算管理
                    企画提案
                    顧客折衝
                    構成案作成
                    アートディレクション
                    GA等を用いた効果測定`}
                />
              </div>
            </div>
            <div className="border border-gray-light">
              <div className="relative flex items-center h-[110px] mt-[-1px] mx-[-1px] p-2 bg-black">
                <p className="absolute top-0 left-0 w-full h-full">
                  <Image
                    src="/about/bg_skill_title_01.jpg"
                    width="960"
                    height="300"
                    alt=""
                    className="w-full h-full object-cover opacity-50"
                    unoptimized
                  />
                </p>
                <p className="relative flex-1 text-center font-medium text-xl text-white">
                  Frontend Development
                </p>
              </div>
              <div className="p-3 text-small leading-1.5">
                <Barometers
                  skills={SKILL_DATA_FRONTEND}
                  inexperienced={`Canvas（WebGL）による演出の実装
                    VRTやE2Eテストの実装
                    既存プロダクトのパフォーマンスチューニング`}
                />
              </div>
            </div>
            <div className="border border-gray-light">
              <div className="relative flex items-center h-[110px] mt-[-1px] mx-[-1px] p-2 bg-black">
                <p className="absolute top-0 left-0 w-full h-full">
                  <Image
                    src="/about/bg_skill_title_03.jpg"
                    width="960"
                    height="300"
                    alt=""
                    className="w-full h-full object-cover opacity-50"
                    unoptimized
                  />
                </p>
                <p className="relative flex-1 text-center font-medium text-xl text-white">
                  Backend Development, <br />
                  Infrastructure
                </p>
              </div>
              <div className="p-3 text-small leading-1.5">
                <Barometers
                  skills={SKILL_DATA_BACKEND}
                  inexperienced={`システム監視
                    AWSの各種製品を組み合わせた設計構築
                    GitHub Actions以外のCI/CDの構築
                    GCPの各種サービスを組み合わせた設計構築`}
                />
              </div>
            </div>
          </div>

          <PrimaryHeader
            text_ja="資格（50音順）"
            text_en="Certification"
            level={2}
            size="medium"
            className="mt-8 mb-4"
          />

          <Certs data={CERTS_DATA} />
        </main>
      </div>
    </>
  );
}
