import { Metadata } from "next";

import { Breadcrumbs } from "@/components/layout/Breadcrumbs";
import { PrimaryHeader } from "@/components/common/PrimaryHeader";
import { EntryList } from "../../_components/archive/EntryList";
import { AllTags } from "../../_components/archive/AllTags";

import { fetchPosts, fetchAllPosts } from "@/lib/microcms";
import { Work, Tool, Tag } from "@/types/microcms";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id } = await params;

  // タグ単体のデータを取得
  const dataTax = (await fetchPosts("tags", {
    filters: `id[equals]${id}`,
  })) as Tag[];

  // タグ名を取得
  const TAG_NAME = dataTax[0].name ?? "";

  return {
    title: `# ${TAG_NAME} | PORTFOLIO-S`,
    description: "Generated by create next app",
  };
}

export async function generateStaticParams() {
  const dataTags = await fetchAllPosts("tags");

  return dataTags.map((tag) => ({
    id: String(tag.id),
  }));
}

export default async function TagsDetail({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;

  // 同一のタグを含む実績・ツールを全件取得し、合算してリリース日の新しい順にソート
  // microCMSではAPIの仕様上、実績とツールをまとめて取得できないため、2回に分けて取得してから合算する
  const DATA_TAG = (await fetchAllPosts("tags", {
    filters: `id[equals]${id}`,
  })) as Tag[];

  const DATA_WORKS = (await fetchAllPosts("works", {
    filters: `tags[contains]${id}`,
  })) as Work[];

  const DATA_TOOLS = (await fetchAllPosts("tools", {
    filters: `tags[contains]${id}`,
  })) as Tool[];

  const DATA_ALL_POSTS = [...DATA_WORKS, ...DATA_TOOLS];

  const DATAS = DATA_ALL_POSTS.sort((a, b) => {
    const dateA = (a.released as unknown as number) ?? 0;
    const dateB = (b.released as unknown as number) ?? 0;
    return dateB - dateA;
  });

  const TAG_NAME = DATA_TAG[0].name ?? "";

  return (
    <>
      {TAG_NAME && (
        <Breadcrumbs
          directory={[{ name: `# ${TAG_NAME}`, href: `/tags/${id}` }]}
        />
      )}
      <div className="px-4">
        <main className="max-w-[1024px] m-auto py-4">
          {DATAS && TAG_NAME && (
            <PrimaryHeader
              text_ja={`タグ「${TAG_NAME}」に一致する実績`}
              text_en={`# ${TAG_NAME}`}
              className="mb-6"
            />
          )}

          {DATAS && <EntryList data={DATAS} />}

          <PrimaryHeader
            text_ja="タグ一覧"
            text_en="See All Tags"
            size="medium"
            className="mt-8 mb-4"
          />
          <AllTags />
        </main>
      </div>
    </>
  );
}
