import type { Metadata } from 'next';

import { Recents } from './_components/front/Recents';
import { Pickup } from './_components/front/Pickup';
import { About } from './_components/front/About';
import { LpBanner } from './_components/front/LpBanner';

import { fetchPosts } from '@/lib/microcms';
import { Tool, Work } from '@/types/microcms';

export const metadata: Metadata = {
  title: 'PORTFOLIO-S',
  description: 'Generated by create next app'
};

export default async function Home() {
  // microCMSから先頭固定表示の実績を取得
  const DATA_PICKUP = (await fetchPosts('works', {
    filters: 'is_sticky[equals]true'
  })) as Work[];
  // microCMSから先頭固定表示ではない実績を5件取得
  const DATA_WORKS = (await fetchPosts('works', {
    limit: 5,
    orders: 'system:default'
    // filters: "is_sticky[equals]false",
  })) as Work[];
  // microCMSから実績（ツール）を5件取得
  const DATA_TOOLS = (await fetchPosts('tools', {
    limit: 5,
    orders: 'system:default'
  })) as Tool[];

  return (
    <>
      {DATA_PICKUP && <Pickup pickups={DATA_PICKUP} />}

      <div className="px-4">
        <LpBanner />

        <div className="flex items-stretch flex-nowrap max-w-[1024px] m-auto">
          <main className="basis-[670px] pb-8 pt-4 pr-3 mr-auto">
            {DATA_WORKS && (
              <Recents
                title_ja="最近の実績"
                title_en="RECENT WORKS"
                detail_title="実績一覧へ"
                detail_href="/works"
                data={DATA_WORKS}
              />
            )}

            {DATA_TOOLS && (
              <Recents
                title_ja="業務で開発した社内ツール"
                title_en="RECENT TOOLS"
                detail_title="ツール一覧へ"
                detail_href="/tools"
                data={DATA_TOOLS}
                className="mt-8"
              />
            )}
          </main>
          <aside className="flex-shrink-1 basis-[300px] pb-8 pl-3 ml-auto border-l border-gray-light">
            <div className="sticky top-0 left-0">
              <About />
            </div>
          </aside>
        </div>
      </div>
    </>
  );
}
