import type { Metadata } from "next";

import { Breadcrumbs } from "@/components/layout/Breadcrumbs";
import { PrimaryHeader } from "@/components/common/PrimaryHeader";
import { EntryList } from "../_components/archive/EntryList";
import { AllTags } from "../_components/archive/AllTags";

import type { Tool } from "@/types/microcms";
import { fetchAllPosts } from "@/lib/microcms";

export const metadata: Metadata = {
  title: "Tools | PORTFOLIO-S",
  description: "Generated by create next app",
};

export default async function Tools() {
  // microCMSから実績を全件取得
  const DATA = (await fetchAllPosts("tools", {
    orders: "system:default",
  })) as Tool[];

  return (
    <>
      <Breadcrumbs directory={[{ name: "Tools", href: "/tools" }]} />
      <div className="px-4">
        <main className="max-w-[1024px] m-auto py-4">
          <PrimaryHeader
            text_ja="ツール一覧"
            text_en="Tools"
            className="mb-6"
          />

          {DATA && <EntryList data={DATA} />}

          <PrimaryHeader
            text_ja="タグ一覧"
            text_en="See All Tags"
            size="medium"
            className="mt-8 mb-4"
          />
          <AllTags />
        </main>
      </div>
    </>
  );
}
