import { Metadata } from 'next';

import { Breadcrumbs } from '@/components/layout/Breadcrumbs';
import { EntryDetail } from '@/app/_components/detail/EntryDetail';

import {
  fetchAllPosts,
  fetchPosts,
  fetchAdjacentPosts,
  generateURL,
} from '@/lib/microcms';
import { Work } from '@/types/microcms';

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id } = await params;

  // idをもとに記事単体のデータを取得
  const DATA = (await fetchPosts('works', {
    filters: `id[equals]${Number(id)}`,
  })) as Work[];

  return {
    title: `${DATA[0].title ?? ''} | Works | PORTFOLIO-S`,
    description: 'Generated by create next app',
  };
}

export async function generateStaticParams() {
  const dataPosts = await fetchAllPosts('works', { fields: 'id' });

  return dataPosts.map((post) => ({
    id: String(post.id),
  }));
}

export default async function WorksDetail({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;

  // 記事単体のデータを取得
  const DATA = (await fetchPosts('works', {
    filters: `id[equals]${Number(id)}`,
  })) as Work[];

  // 前後の記事データを取得
  const DATA_PAGER = await fetchAdjacentPosts('works', DATA[0].id);

  if (!DATA || !DATA_PAGER) return null;

  return (
    <>
      {DATA && (
        <Breadcrumbs
          directory={[
            { name: 'Works', href: '/works' },
            {
              name: `${DATA[0].title}`,
              href: `${generateURL('works', DATA[0].id)}`,
            },
          ]}
        />
      )}
      {DATA && <EntryDetail data={DATA[0]} dataPager={DATA_PAGER} />}
    </>
  );
}
