import type { Metadata } from 'next';

import { Breadcrumbs } from '@/components/layout/Breadcrumbs';
import { PrimaryHeader } from '@/components/common/PrimaryHeader';
import { Separator } from '@/components/common/Separator';
import { EntryList } from '../_components/archive/EntryList';
import { AllTags } from '../_components/archive/AllTags';

import type { Work, Tool, Era } from '@/types/microcms';
import { fetchPosts } from '@/lib/microcms';

interface ResultsProps {
  heading?: string;
  data: (Work | Tool)[];
}

export const metadata: Metadata = {
  title: 'Managements | PORTFOLIO-S',
  description: 'Generated by create next app'
};

export default async function Managements() {
  // タグに「PL」を含む実績・ツールを全件取得し、合算してリリース日の新しい順にソート
  // microCMSではAPIの仕様上、実績とツールをまとめて取得できないため、2回に分けて取得してから合算する
  const DATA_MANAGEMENTS_1 = (await fetchPosts('works', {
    orders: 'system:default',
    filters: 'tags[contains]pl'
  })) as Work[];

  const DATA_MANAGEMENTS_2 = (await fetchPosts('tools', {
    orders: 'system:default',
    filters: 'tags[contains]pl'
  })) as Tool[];

  const DATA_MANAGEMENTS = [...DATA_MANAGEMENTS_1, ...DATA_MANAGEMENTS_2].sort(
    (a, b) => (a.released < b.released ? 1 : -1)
  );

  const DATA_ERAS = (await fetchPosts('eras', {
    orders: 'system:default'
  })) as Era[];

  // 年代ごとに実績を分類
  const RESULTS: ResultsProps[] = DATA_ERAS.map((era) => ({
    heading: era.name ?? '',
    data: DATA_MANAGEMENTS.filter((data) => data.era.id === era.id)
  }));

  return (
    <>
      <Breadcrumbs
        directory={[{ name: 'Managements', href: '/managements' }]}
      />
      <div className="px-4">
        <main className="max-w-[1024px] m-auto py-4">
          <PrimaryHeader
            text_ja="PLとしての実績一覧"
            text_en="Managements"
            className="mb-6"
          />

          {RESULTS && (
            <EntryList
              heading={RESULTS[2].heading}
              annotation={`事業会社Aにて管理を行なったプロジェクト一覧。
            引き続きPLとしてプロジェクト管理に専念しました。
            担当範囲が広く、専門性も進行力も求められ、自身のなかでプロジェクト管理の道に進む大きなターニングポイントになりました。`}
              data={RESULTS[2].data}
            />
          )}

          <Separator />

          {RESULTS && (
            <EntryList
              heading={RESULTS[1].heading}
              annotation={`制作会社Bにて管理を行なったプロジェクト一覧。
            PL（プロジェクトリーダー）として、主に要件定義や設計を行い、外注先の選定から量産管理を行うことで、開発の効率化を図りました。自身もまた基本設計やコンポーネント設計を行なっております。
            また、工程の再定義を行うことで生産性向上に寄与したり、複数チームや複数社の取りまとめを行っておりました。`}
              data={RESULTS[1].data}
            />
          )}

          <PrimaryHeader
            text_ja="タグ一覧"
            text_en="See All Tags"
            size="medium"
            className="mt-8 mb-4"
          />
          <AllTags />
        </main>
      </div>
    </>
  );
}
