import type { Metadata } from 'next';
import { Fragment } from 'react';
import { v4 as uuidv4 } from 'uuid';

import { Breadcrumbs } from '@/components/layout/Breadcrumbs';
import { PrimaryHeader } from '@/components/common/PrimaryHeader';
import { Separator } from '@/components/common/Separator';
import { EntryList } from '../_components/archive/EntryList';
import { AllTags } from '../_components/archive/AllTags';

import type { Work, Tool, Era } from '@/types/microcms';
import { fetchPosts } from '@/lib/microcms';

interface ResultsProps {
  heading?: string;
  data: (Work | Tool)[];
  detail?: string;
}

export const metadata: Metadata = {
  title: 'Managements | PORTFOLIO-S',
  description: 'Generated by create next app'
};

export default async function Managements() {
  // タグに「PL」を含む実績・ツールを全件取得し、合算してリリース日の新しい順にソート
  // microCMSではAPIの仕様上、実績とツールをまとめて取得できないため、2回に分けて取得してから合算する
  const DATA_MANAGEMENTS_1 = (await fetchPosts('works', {
    orders: 'system:default',
    filters: 'tags[contains]pl'
  })) as Work[];

  const DATA_MANAGEMENTS_2 = (await fetchPosts('tools', {
    orders: 'system:default',
    filters: 'tags[contains]pl'
  })) as Tool[];

  const DATA_MANAGEMENTS = [...DATA_MANAGEMENTS_1, ...DATA_MANAGEMENTS_2].sort(
    (a, b) => (a.released < b.released ? 1 : -1)
  );

  const DATA_ERAS = (await fetchPosts('eras', {
    orders: 'system:default'
  })) as Era[];

  // 年代ごとに実績を分類
  const RESULTS: ResultsProps[] = DATA_ERAS.map((era) => ({
    heading: era.name ?? '',
    data: DATA_MANAGEMENTS.filter((data) => data.era.id === era.id),
    detail: era.detail_management
  }))
    .filter((result) => result.data.length > 0)
    .reverse(); // データが1件もない年代は表示しない

  return (
    <>
      <Breadcrumbs
        directory={[{ name: 'Managements', href: '/managements' }]}
      />
      <div className="px-4">
        <main className="max-w-[1024px] m-auto py-4">
          <PrimaryHeader
            text_ja="PLとしての実績一覧"
            text_en="Managements"
            className="mb-6"
          />

          {RESULTS.map((result, i) => (
            <Fragment key={result.heading ?? uuidv4()}>
              <EntryList
                heading={result.heading ?? ''}
                annotation={result.detail ?? ''}
                data={result.data}
              />
              <Separator />
            </Fragment>
          ))}

          <PrimaryHeader
            text_ja="タグ一覧"
            text_en="See All Tags"
            size="medium"
            className="mt-8 mb-4"
          />
          <AllTags />
        </main>
      </div>
    </>
  );
}
