import { Metadata } from 'next';

import { Breadcrumbs } from '@/components/layout/Breadcrumbs';
import { EntryDetail } from '@/app/_components/detail/EntryDetail';

import {
  fetchAllPosts,
  fetchPosts,
  fetchAdjacentPosts,
  generateURL
} from '@/lib/microcms';
import { Tool } from '@/types/microcms';

export async function generateMetadata({
  params
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id } = await params;

  // idをもとに記事単体のデータを取得
  const DATA = (await fetchPosts('tools', {
    filters: `id[equals]${Number(id)}`
  })) as Tool[];

  return {
    title: `${DATA[0].title ?? ''} | Tools | PORTFOLIO-S`,
    description: 'Generated by create next app'
  };
}

export async function generateStaticParams() {
  const dataTools = await fetchAllPosts('tools', { fields: 'id' });

  return dataTools.map((tool) => ({
    id: String(tool.id)
  }));
}

export default async function ToolsDetail({
  params
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;

  // 記事単体のデータを取得
  const DATA = (await fetchPosts('tools', {
    filters: `id[equals]${Number(id)}`
  })) as Tool[];

  // 前後の記事データを取得
  const DATA_PAGER = await fetchAdjacentPosts('tools', DATA[0].id);

  if (!DATA || !DATA_PAGER) return null;

  return (
    <>
      {DATA && (
        <Breadcrumbs
          directory={[
            { name: 'Tools', href: '/tools' },
            {
              name: `${DATA[0].title}`,
              href: `${generateURL('tools', DATA[0].id)}`
            }
          ]}
        />
      )}
      {DATA && <EntryDetail data={DATA[0]} dataPager={DATA_PAGER} />}
    </>
  );
}
