import type { Metadata } from 'next';
import { Fragment } from 'react';
import { v4 as uuidv4 } from 'uuid';

import { Breadcrumbs } from '@/components/layout/Breadcrumbs';
import { PrimaryHeader } from '@/components/common/PrimaryHeader';
import { Separator } from '@/components/common/Separator';
import { EntryList } from '../_components/archive/EntryList';
import { AllTags } from '../_components/archive/AllTags';

import type { Work, Era } from '@/types/microcms';
import { fetchPosts, fetchAllPosts } from '@/lib/microcms';

interface ResultsProps {
  heading: string;
  data: Work[];
  detail?: string;
}

export const metadata: Metadata = {
  title: 'Works | PORTFOLIO-S',
  description: 'Generated by create next app'
};

export default async function Works() {
  // microCMSから実績を全件取得
  const DATA_WORKS = (await fetchAllPosts('works', {
    orders: 'system:default'
  })) as Work[];

  const DATA_ERAS = (await fetchPosts('eras', {
    orders: 'system:default'
  })) as Era[];

  // 年代ごとに実績を分類
  const RESULTS: ResultsProps[] = DATA_ERAS.map((era) => ({
    heading: era.name ?? '',
    data: DATA_WORKS.filter(
      (data) => data.era.id === era.id && 'is_sticky' in data
    ),
    detail: era.detail_works
  }))
    .filter((result) => result.data.length > 0)
    .reverse(); // データが1件もない年代は表示しない

  return (
    <>
      <Breadcrumbs directory={[{ name: 'Works', href: '/works' }]} />
      <div className="px-4">
        <main className="max-w-[1024px] m-auto py-4">
          <PrimaryHeader text_ja="実績一覧" text_en="Works" className="mb-6" />

          {RESULTS.map((result, i) => (
            <Fragment key={result.heading ?? uuidv4()}>
              <EntryList
                heading={result.heading ?? ''}
                annotation={result.detail ?? ''}
                data={result.data}
              />
              <Separator />
            </Fragment>
          ))}

          <PrimaryHeader
            text_ja="タグ一覧"
            text_en="See All Tags"
            size="medium"
            className="mt-8 mb-4"
          />

          <AllTags />
        </main>
      </div>
    </>
  );
}
