import type { Metadata } from "next";

import { Breadcrumbs } from "@/components/layout/Breadcrumbs";
import { PrimaryHeader } from "@/components/common/PrimaryHeader";
import { Separator } from "@/components/common/Separator";
import { EntryList } from "../_components/archive/EntryList";
import { AllTags } from "../_components/archive/AllTags";

import type { Work, Era } from "@/types/microcms";
import { fetchPosts, fetchAllPosts } from "@/lib/microcms";

interface ResultsProps {
  heading: string;
  data: Work[];
}

export const metadata: Metadata = {
  title: "Works | PORTFOLIO-S",
  description: "Generated by create next app",
};

export default async function Works() {
  // microCMSから実績を全件取得
  const DATA_WORKS = (await fetchAllPosts("works", {
    orders: "system:default",
  })) as Work[];

  const DATA_ERAS = (await fetchPosts("eras", {
    orders: "system:default",
  })) as Era[];

  // 年代ごとに実績を分類
  const RESULTS: ResultsProps[] = DATA_ERAS.map((era) => ({
    heading: era.name ?? "",
    data: DATA_WORKS.filter(
      (data) => data.era.id === era.id && "is_sticky" in data,
    ),
  }));

  return (
    <>
      <Breadcrumbs directory={[{ name: "Works", href: "/works" }]} />
      <div className="px-4">
        <main className="max-w-[1024px] m-auto py-4">
          <PrimaryHeader text_ja="実績一覧" text_en="Works" className="mb-6" />

          {RESULTS && (
            <EntryList
              heading={RESULTS[2].heading}
              annotation={`事業会社Aで自社サービス「はたらこねっと」のエンハンスと、「はたらこマガジン」の新規立ち上げに携わりました。
              これまでと異なり自身はPLとしてプロジェクト管理に専念し、フロントエンド開発はチームメンバーに任せる形で進めておりました。
              また、プロジェクトの進行にあたり、社内の関係者との調整や、要件定義・設計・進行管理を行っておりました。`}
              data={RESULTS[2].data}
            />
          )}

          <Separator />

          {RESULTS && (
            <EntryList
              heading={RESULTS[1].heading}
              annotation={`制作会社Bにてフロントエンド開発と、プロジェクト管理を担当。
              開発では、大規模・中規模サイトの設計構築を担当。
              プロジェクト管理では自身で設計したサイトの量産管理・工程の再定義・複数チームや複数社の取りまとめを行っておりました。`}
              data={RESULTS[1].data}
            />
          )}

          <Separator />

          {RESULTS && (
            <EntryList
              heading={RESULTS[0].heading}
              annotation={`制作会社Aにてフロントエンド開発を担当。
              大規模サイトの保守運用からキャリアを開始したのち、代理店より受託したサイトの設計構築を担当。リッチな演出のブランドサイトやLPの開発を行っておりました。`}
              data={RESULTS[0].data}
            />
          )}

          <PrimaryHeader
            text_ja="タグ一覧"
            text_en="See All Tags"
            size="medium"
            className="mt-8 mb-4"
          />

          <AllTags />
        </main>
      </div>
    </>
  );
}
