import { Metadata } from 'next';

import { Breadcrumbs } from '@/components/layout/Breadcrumbs';
import { PageDetail } from '@/app/feature/_components/PageDetail';

export const metadata: Metadata = {
  title: 'ポートフォリオ Jamstackリアーキテクチャ | PORTFOLIO-S',
  description: 'Generated by create next app'
};

export default function Feature() {
  return (
    <>
      <Breadcrumbs
        directory={[
          { name: 'ポートフォリオ Jamstackリアーキテクチャ', href: '/feature' }
        ]}
      />
      <PageDetail />
    </>
  );
}
